theme: jekyll-theme-hacker
title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
title: [The title of your site]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
